import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BookMarked,
  BookOpen,
  Calendar,
  CalendarCheck,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDashed,
  CircleHelp,
  Clock,
  CloudCheck,
  Coins,
  Delete,
  EyeOff,
  Feather,
  Flag,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  GraduationCap,
  Hourglass,
  House,
  Info,
  Landmark,
  Leaf,
  Lightbulb,
  ListChecks,
  Lock,
  type LucideIcon,
  Map as MapIcon,
  MessageCircle,
  Minus,
  Newspaper,
  NotebookPen,
  Percent,
  Play,
  Printer,
  Plus,
  RotateCcw,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Shuffle,
  Sigma,
  Smartphone,
  Sparkle,
  Sparkles,
  Star,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Triangle,
  Trophy,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react-native';

import { colors } from '@/theme/tokens';

/** Íconos de interfaz: Lucide, trazo de 2 px y puntas redondas (design system → Icon). */
const ICONS = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bell: Bell,
  'book-marked': BookMarked,
  book: BookOpen,
  'calendar-check': CalendarCheck,
  calendar: Calendar,
  camera: Camera,
  chart: ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-dashed': CircleDashed,
  'circle-help': CircleHelp,
  clock: Clock,
  'cloud-check': CloudCheck,
  coins: Coins,
  delete: Delete,
  'eye-off': EyeOff,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  flask: FlaskConical,
  gem: Gem,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hourglass: Hourglass,
  house: House,
  info: Info,
  landmark: Landmark,
  leaf: Leaf,
  lightbulb: Lightbulb,
  'list-checks': ListChecks,
  lock: Lock,
  map: MapIcon,
  'message-circle': MessageCircle,
  minus: Minus,
  newspaper: Newspaper,
  'notebook-pen': NotebookPen,
  percent: Percent,
  play: Play,
  printer: Printer,
  plus: Plus,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  search: Search,
  send: Send,
  settings: Settings,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  sigma: Sigma,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  timer: Timer,
  trash: Trash2,
  'trending-up': TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const isIconName = (n: string): n is IconName => n in ICONS;

type Props = { name: IconName; size?: number; color?: string; strokeWidth?: number };

export function Icon({ name, size = 22, color = colors.ink, strokeWidth = 2 }: Props) {
  const C = ICONS[name];
  return <C size={size} color={color} strokeWidth={strokeWidth} />;
}
